### ISSUE TITLE
Search API changed in recent Phabricator

### ISSUE THREAD

**Issue by mmm444** [mmm444/ijphab#4]
When searching on updated Phabricator I got

    Parameter "fullText" is no longer supported. Use method "maniphest.search" with the "query" constraint instead.

**Comment by ghost** [comment]
I also ran into this. How do I update to version 0.4? It does not appear in the plugin list.

**Comment by mmm444** [comment]
Sorry. I have not yet published the new version to the JetBrains repository. I will do it in a day or two.
